# Generated by Django 3.1.4 on 2022-05-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycoonConstruction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='bidcontractor',
            name='project_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bidvendor',
            name='project_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
