# Generated by Django 3.1.4 on 2022-05-24 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tycoonConstruction', '0002_auto_20220525_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidvendor',
            old_name='projects',
            new_name='projectass',
        ),
    ]
