# Generated by Django 3.1.4 on 2022-05-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tycoonConstruction', '0003_auto_20220525_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidvendor',
            old_name='projectass',
            new_name='projects',
        ),
    ]
