# Generated by Django 3.1.4 on 2022-05-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tycoonConstruction', '0004_auto_20220525_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='first_name',
            new_name='project_assigned_to',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='last_name',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='bidcontractor',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='bidvendor',
            name='project_name',
        ),
        migrations.AlterField(
            model_name='bidcontractor',
            name='projects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tycoonConstruction.projects'),
        ),
        migrations.AlterField(
            model_name='bidvendor',
            name='projects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tycoonConstruction.projects'),
        ),
    ]
